[global]

# Global configuration options for Streamlit

[server]
# Server configuration
port = 8501
maxUploadSize = 50

[theme]
# Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
# Browser configuration
gatherUsageStats = false
